const countries = [
  { label: '🇺🇸 United States', code: '+1' },
  { label: '🇬🇧 United Kingdom', code: '+44' },
  { label: '🇦🇺 Australia', code: '+61' },
  { label: '🇮🇳 India', code: '+91' },
  { label: '🇩🇪 Germany', code: '+49' },
  { label: '🇫🇷 France', code: '+33' },
  { label: '🇮🇹 Italy', code: '+39' },
  { label: '🇪🇸 Spain', code: '+34' },
  { label: '🇧🇷 Brazil', code: '+55' },
  { label: '🇨🇳 China', code: '+86' },
  { label: '🇯🇵 Japan', code: '+81' },
  { label: '🇷🇺 Russia', code: '+7' },
  { label: '🇿🇦 South Africa', code: '+27' },
  { label: '🇲🇽 Mexico', code: '+52' },
  { label: '🇰🇷 South Korea', code: '+82' },
  { label: '🇹🇷 Turkey', code: '+90' },
  { label: '🇸🇦 Saudi Arabia', code: '+966' },
  {
    label: '🇦🇪 United Arab Emirates',
    code: '+971',
  },
  { label: '🇦🇷 Argentina', code: '+54' },
  { label: '🇨🇭 Switzerland', code: '+41' },
  { label: '🇳🇱 Netherlands', code: '+31' },
  { label: '🇸🇪 Sweden', code: '+46' },
  { label: '🇳🇴 Norway', code: '+47' },
  { label: '🇩🇰 Denmark', code: '+45' },
  { label: '🇫🇮 Finland', code: '+358' },
  { label: '🇧🇪 Belgium', code: '+32' },
  { label: '🇵🇱 Poland', code: '+48' },
  { label: '🇮🇩 Indonesia', code: '+62' },
  { label: '🇲🇾 Malaysia', code: '+60' },
  { label: '🇵🇭 Philippines', code: '+63' },
  { label: '🇸🇬 Singapore', code: '+65' },
  { label: '🇹🇭 Thailand', code: '+66' },
  { label: '🇳🇿 New Zealand', code: '+64' },
];

export default countries;
